default_context:
  project_name: 'wealth-management-relation-workspace'
  project_slug: 'wealth-management-relation-workspace'
  domain_main: 'citiwealth.com'
  domain_staging: 'stag.citiwealth.com'
  docker_swarm_stack_name_main: 'citiwealth-com'
  docker_swarm_stack_name_staging: 'stag-citiwealth-com'
  secret_key: '$1'
  first_superuser: 'admin@citiwealth.com'
  first_superuser_password: 'password'
  backend_cors_origins: '"http://localhost"'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@citiwealth.com'
  postgres_password: 'password'
  pgadmin_default_user: 'admin@citiwealth.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'citiwealth.com'
  traefik_constraint_tag_staging: 'stag.citiwealth.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: 'citiwealth'
  docker_image_backend: 'citiwealthbackend'
  docker_image_celeryworker: 'citiwealthceleryworker'
  docker_image_frontend: 'citiwealthfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
